### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by mchirlin** [benbarkay/htmltopdf-java#35]
I am getting the following error, despite having the depencies installed (as far as I can tell).  Are there any other steps I need to take?

```
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library '/usr/local/appian/ae/tomcat/apache-tomcat/temp/io.woo.htmltopdf/wkhtmltox/0.12.5/libwkhtmltox.so': Native library (usr/local/appian/ae/tomcat/apache-tomcat/temp/io.woo.htmltopdf/wkhtmltox/0.12.5/libwkhtmltox.so) not found in resource path (/usr/local/appian/ae/tomcat/apache-tomcat/bin/bootstrap.jar:/usr/local/appian/ae/tomcat/apache-tomcat/bin/tomcat-juli.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
	at io.woo.htmltopdf.wkhtmltopdf.WkHtmlToPdfLoader.load(WkHtmlToPdfLoader.java:39)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

```
[appian@apac-app ~]$ sudo yum install glibc libX11 libXext libXrender openssl libstdc++ freetype fontconfig
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
 * amzn-main-7: packages.us-east-1.amazonaws.com
 * amzn-updates-7: packages.us-east-1.amazonaws.com
 * base: d36uatko69830t.cloudfront.net
 * epel: iad.mirror.rackspace.com
 * extras: d36uatko69830t.cloudfront.net
 * updates: d36uatko69830t.cloudfront.net
Package glibc-2.17-292.el7.x86_64 already installed and latest version
Package libX11-1.6.7-2.el7.x86_64 already installed and latest version
Package libXext-1.3.3-3.el7.x86_64 already installed and latest version
Package libXrender-0.9.10-1.el7.x86_64 already installed and latest version
Package 1:openssl-1.0.2k-19.el7.x86_64 already installed and latest version
Package libstdc++-4.8.5-39.el7.x86_64 already installed and latest version
Package freetype-2.8-14.el7.x86_64 already installed and latest version
Package fontconfig-2.13.0-4.3.el7.x86_64 already installed and latest version
Nothing to do
```

**Comment by Shaun-Sheppard** [comment]
I too am experiencing the same issue.

sudo yum install glibc libX11 libXext libXrender openssl libstdc++ freetype fontconfig
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.serverspace.co.uk
 * extras: mirror.as29550.net
 * updates: mirrors.melbourne.co.uk
Package glibc-2.17-292.el7.x86_64 already installed and latest version
Package libX11-1.6.7-2.el7.x86_64 already installed and latest version
Package libXext-1.3.3-3.el7.x86_64 already installed and latest version
Package libXrender-0.9.10-1.el7.x86_64 already installed and latest version
Package 1:openssl-1.0.2k-19.el7.x86_64 already installed and latest version
Package libstdc++-4.8.5-39.el7.x86_64 already installed and latest version
Package freetype-2.8-14.el7.x86_64 already installed and latest version
Package fontconfig-2.13.0-4.3.el7.x86_64 already installed and latest version
Nothing to do

Part of the error I receive is;

> error=Internal Server Error, exception=java.lang.IllegalStateException, message=java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: Unable to load library '/opt/tomcat/temp/io.woo.htmltopdf/wkhtmltox/0.12.5/libwkhtmltox.so': Native library (opt/tomcat/temp/io.woo.htmltopdf/wkhtmltox/0.12.5/libwkhtmltox.so) not found in resource path ([file:/opt/tomcat/webapps/ROOT/WEB-INF/classes/, file:/opt/tomcat/webapps/ROOT/WEB-INF/lib/spring-boot-starter-aop-1.4.0.RELEASE.jar

**Comment by aniket147** [comment]
@mchirlin  @shepparddigital Getting same issue on Amazon Linux machine. Is there any solution you guys found?
